#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build 
touch ./_site/.nojekyll # this file tells gh-pages that there is no need to build
touch ./_site/CNAME
echo 'cjcm567.github.io' > ./_site/CNAME